export const SET_INPUT_IMAGE = 'SET_INPUT_IMAGE';
export const EVOLUTION_STATE = 'EVOLUTION_STATE';
export const CHANGE_NUM_VERTICES = 'CHANGE_NUM_VERTICES';
export const CHANGE_MAX_POLYGONS = 'CHANGE_MAX_POLYGONS';
